version: '3'
services:
  app:
    image: xml-rastro:2.0
    container_name: xml_app
    ports:
      - "1290:1290"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl  # Para certificados SSL
